version: "3"

services:
    db:
        container_name: project-name-postgres-prod
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=$PGUSER
            - POSTGRES_PASSWORD=$PGPASSWORD
            - POSTGRES_DB=$PGDATABASE
        volumes:
            - project-name-database:/var/lib/postgresql/data
        networks:
            - project-name-network

    app:
        container_name: project-name-app-prod
        command: yarn start:prod
        environment:
            - NODE_ENV=$NODE_ENV
            - PGHOST=$PGHOST
            - PGPORT=$PGPORT
            - PGUSER=$PGUSER
            - PGPASSWORD=$PGPASSWORD
            - PGDATABASE=$PGDATABASE
        image: project-name:latest
        restart: always
        ports:
            - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - project-name-network
        depends_on:
            - db

networks:
    project-name-network:
        external: true

volumes:
    project-name-database: {}