version: "3"

services:
    devDB:
        container_name: project-name-postgres-dev
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
            - POSTGRES_DB=project-name-dev-db
        volumes:
            - project-name-database-dev:/var/lib/postgresql/data
        networks:
            - project-name-network-dev
    
    testDB:
        container_name: project-name-postgres-test
        image: postgres:14-alpine
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
            - POSTGRES_DB=project-name-test-db
        volumes:
            - ./docker-volumes/postgresql-test:/var/lib/postgresql
        networks:
            - project-name-network-dev

    app:
        container_name: project-name-app-dev
        command: yarn start:dev
        environment:
            - NODE_ENV=development
            - PGHOST=devDB
            - PGPORT=5432
            - PGUSER=root
            - PGPASSWORD=toor
            - PGDATABASE=project-name-dev-db
        image: project-name-dev:latest
        ports:
            - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - project-name-network-dev
        depends_on:
            - devDB
            - testDB

networks:
    project-name-network-dev:
        external: true

volumes:
    project-name-database-dev: {}