version: '3'
services:
  DevDB:
    container_name: project-name-postgres-dev
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=project-name-dev-db
    volumes:
      - ./docker-volumes/postgresql-dev:/var/lib/postgresql